App\Request\UploadImageRequest:
  properties:
    uploadedFile:
      - Image:
          #mimeTypesMessage: "this id not message"
          maxSize: 2m
          maxSizeMessage: "Image size over 2M"

App\Request\CreateInteractionRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    type:
      - NotBlank: ~

App\Request\CreateAnimeRequest:
  properties:
    name:
      - NotBlank: ~
    categoryID:
      - NotBlank: ~
    mainImage:
      - NotBlank: ~

App\Request\CreateCategoryRequest:
  properties:
    name:
      - NotBlank: ~
    description:
      - NotBlank: ~

App\Request\CreateCommentRequest:
  properties:
    userID:
      - NotBlank: ~
    animeID:
      - NotBlank: ~
    comment:
      - NotBlank: ~